#!/bin/bash

#This script is used to test the command instructions from README.md
declare -a mandatory
mandatory=(
  GCP_ZONE
  GCP_PROJECT
  GKE_CLUSTER_NAME
  GKE_CLUSTER_NUM_NODES
  GKE_CLUSTER_MACHINE_TYPE
  HELM_RELEASE
  NAMESPACE
)

check_variables() {
  MISSING=false
  for var in "${mandatory[@]}"; do
    [[ -z "${!var:-}" ]] && {
      echo "${RED}Environment variable $var must be set${NC}"
      MISSING=true
    }
  done
  [[ "$MISSING" == true ]] && exit 1
}

check_variables
# Delete CD Agent helm release
helm uninstall $HELM_RELEASE-agents -n $NAMESPACE
# Delete CD Server helm release
helm uninstall $HELM_RELEASE -n $NAMESPACE
# Delete GKE cluster
gcloud container clusters delete $GKE_CLUSTER_NAME --zone $GCP_ZONE --project $GCP_PROJECT